language: go
dist: bionic
go: "1.13.x"

script:
- ./build-release.sh

if: tag IS present

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
